### ISSUE TITLE
MOM client shows operations different from action taken

### ISSUE THREAD

**Issue by quevas13** [InternetOfPeers/mom-client#25]
**Describe the bug**
If I UPDATE a message the operation shown in "Operation list" is a DELETE and I think more operations are mixed up.

**To Reproduce**
1. ADD a message
2. UPDATE the same message
3. Go to Operation list and the message type is DELETE even if on ethereum the hex code is 3 as per [specs](https://github.com/InternetOfPeers/mom-spec#list-of-supported-operations-and-messages)

**Expected behavior**
All operations should be of the correct type

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Browser: Google Chrome Version 84.0.4147.105 (Official Build) (64-bit)

Looking at the code I think there is an old implementation of the specs.
According to the [specs](https://github.com/InternetOfPeers/mom-spec#list-of-supported-operations-and-messages) the hex code for DELETE is 2 while in the [index.js](https://github.com/InternetOfPeers/mom-client/blob/0bc89e21f7c43bf752d6237450e4ffb501b8073f/src/index.js#L375) is 3. The ADD operation works because the code is 0 in both specs and index.js. The mom [constants](https://github.com/InternetOfPeers/mom-js/blob/develop/src/constants.js) reflect the correct values.

If my guess will prove correct I would be glad to work on it.

**Comment by Neurone** [comment]
Good spot! Thanks :)
